name: 'CI'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: true
  test:
    name: Build (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Set up npm
        run: npm install --global npm@11.19.0
      - name: Install Dependencies
        run: npm ci
      - name: Check Formatting
        run: npm run format:check
      - name: Build
        run: npm run build
      - name: Check Peer Dependencies
        run: node dist/cli.js
